-- ============================================
-- CATALOG 2026 CATEGORY CORRECTIONS
-- Fixing products with wrong categories
-- ============================================
-- Total updates: 249

UPDATE products SET category = 'shavings' WHERE id = 78; -- WORLD CUP LARGE 10 CU. FT. SHAVINGS | was 'other' -> 'shavings'
UPDATE products SET category = 'shavings' WHERE id = 87; -- OBEC LARGE SHAVINGS | was 'other' -> 'shavings'
UPDATE products SET category = 'shavings' WHERE id = 69; -- KING LARGE FLAKE | was 'other' -> 'shavings'
UPDATE products SET category = 'shavings' WHERE id = 38; -- SHOWTIME LARGE FLAKE | was 'other' -> 'shavings'
UPDATE products SET category = 'shavings' WHERE id = 28; -- BEAVER SHAVINGS | was 'other' -> 'shavings'
UPDATE products SET category = 'shavings' WHERE id = 54; -- FAST TRACK BLEND SHAVINGS (RED) | was 'other' -> 'shavings'
UPDATE products SET category = 'shavings' WHERE id = 56; -- FAST TRACK FINE SHAVINGS | was 'horse' -> 'shavings'
UPDATE products SET category = 'shavings' WHERE id = 153; -- RED GRANDIS FINE SHAVINGS | was 'other' -> 'shavings'
UPDATE products SET category = 'shavings' WHERE id = 66; -- WD FINE SHAVINGS | was 'other' -> 'shavings'
UPDATE products SET category = 'shavings' WHERE id = 108; -- WD FLAKE SHAVINGS | was 'other' -> 'shavings'
UPDATE products SET category = 'shavings' WHERE id = 30; -- WD PELLETED BEDDING | was 'other' -> 'shavings'
UPDATE products SET category = 'shavings' WHERE id = 82; -- BALED STRAW | was 'other' -> 'shavings'
UPDATE products SET category = 'hay' WHERE id = 73; -- HAY- 1ST CUT 3 STRING TIMOTHY | was 'horse' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 72; -- HAY- 2ND CUT 3 STRING TIMOTHY | was 'horse' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 104; -- HAY- GRASSY 2ND CUT TIMOTHY 3STRING | was 'horse' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 32; -- HAY - 3 STRING ALFALFA | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 42; -- HAY - 3 STRING ORCHARD | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 125; -- 3 STRING TEFF | was 'horse' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 101; -- HAY - FIRST CUT ALBERTA TIMOTHY | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 98; -- HAY- 2ND CUT ALBERTA | was 'horse' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 37; -- HAY - PREMIUM TA | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 53; -- HAY - SPECIAL RESERVE T/A | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 116; -- COMPRESSED T/A | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 31; -- HAY - QUEBEC T/A | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 132; -- HAY - TWYLA | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 48; -- HAY - VALLEY GREEN | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 52; -- HAY - SUPERGRASS | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 57; -- COMPRESSED ALFALFA | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 198; -- HAY - PEANUT | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 126; -- LUCERNE HI-FIBER GOLD NO MOLASSES | was 'horse' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 147; -- ANDERSON ALFALFA TIMOTHY CUBES | was 'horse' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 59; -- STANDLEE ALFALFA CHOPPED 40LB | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 503; -- STANDLEE TIMOTHY CHOPPED | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 145; -- ALFALFA CUBES 50LB | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 39; -- ANDERSON ALFALFA PELLETS 40LB | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 504; -- STANDLEE TIMOTHY GRASS PELLETS | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 50; -- MINI ALFALFA CUBES 50LB | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 501; -- STANDLEE ALFALFA TIMOTHY PELLETS | was 'other' -> 'hay'
UPDATE products SET category = 'hay' WHERE id = 40; -- ANDERSON TIMOTHY PELLETS 40LB | was 'other' -> 'hay'
UPDATE products SET category = 'horse' WHERE id = 196; -- CADENCE ULTRA BUCKEYE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 120; -- EQ8 GUT HEALTH BUCKEYE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 123; -- EQ8 SENIOR BUCKEYE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 190; -- GRO N WIN BUCKEYE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 183; -- SAFE N EASY PELLET BUCKEYE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 222; -- Ultimate Finish 25 Buckeye | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 99; -- FIBERFORCE GASTRO CAVALOR | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 67; -- MASH & MIX 15KG CAVALOR | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 100; -- PIANISSIMO CAVALOR | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 174; -- STRUCOMIX ORIGINAL CAVALOR | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 94; -- WHOLEGAIN CAVALOR | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 65; -- COOLSTANCE COPRA STANCE EQUITEC | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 171; -- WHOLEFOOD HORSE FEED CRYPTO AERO REGULAR | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 35; -- WILD FORAGE CRYPTO AERO | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 136; -- FIBREBEET 44LB EMERALD VALLEY | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 109; -- SPEEDI BEET 44LB EMERALD VALLEY | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 473; -- CF CRIMPED OATS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 110; -- STEAM ROLLED OATS 50LB (OATMEAL) | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 152; -- SOYBEAN MEAL 50LBB | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 88; -- WHEAT BRAN 40LB | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 111; -- WHOLE FLAX 50LB | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 200; -- CF WHOLE OATS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 79; -- HALLWAY FIBRENERGY | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 80; -- HALLWAY LUMINANCE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 86; -- COOL MIX 44LB (MUESLI-WITHOUT-OATS) HAVENS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 63; -- DRAVERSBROK 55LB HAVENS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 219; -- Endurance 14 Muesli Havens | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 33; -- PERFORMANCE 14 44 LB HAVENS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 220; -- Power Plus Mix 44lb Havens | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 93; -- NATURAL BALANCE 44LB -MOLASSES FREE - HAVENS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 64; -- SENIOR CRUMBS HAVENS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 201; -- KER ALL-PHASE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 41; -- KER RE-LEVE ORIGINAL | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 166; -- KER RE-LEVE SPORT | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 96; -- PROFORCE FUEL | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 97; -- PROFORCE SENIOR | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 112; -- SAFECHOICE SENIOR | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 68; -- SAFECHOICE SPECIAL CARE / STARCH WI SE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 130; -- TRIUMPH FIBER PLUS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 62; -- TRIUMPH PROFESSIONAL 14% PELLET | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 135; -- SOUTHEAST 12/8 HORSE PELLET | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 146; -- TRIUMPH TRIPLE 10 | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 113; -- STOCK AND STABLE SWEET | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 172; -- EMPOWER DIGESTIVE BALANCE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 119; -- EMPOWER TOPLINE BALANCE 40LB | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 71; -- PROELITE GRASS ADVANTAGE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 193; -- PROELITE GROWTH | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 89; -- PROELITE OMEGA ADVANTAGE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 90; -- PROELITE PERFORMANCE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 51; -- PROELITE SENIOR | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 170; -- PROELITE TOPLINE ADVANTAGE | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 131; -- COMFORT MASH 40LB RED MILLS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 107; -- COMPETITION 10 MIX 44LB RED MILLS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 103; -- COMPETITION 12 MIX 44LB RED MILLS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 162; -- COMPETITION 14 MIX 44LB RED MILLS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 60; -- COOL N CONDITION PELLETS 55LB RED MILLS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 158; -- HORSE CARE 10 PELLETS 55LB RED MILLS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 75; -- HORSE CARE 14 PELLETS 55LB RED MILLS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 133; -- HORSE CARE 10 MIX RED MILLS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 61; -- HORSE CARE 14 MIX RED MILLS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 76; -- HORSE CARE ULTRA RED MILLS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 77; -- HORSE CARE MASH RED MILLS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 74; -- DEFINE AND SHINE RED MILLS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 137; -- SENTINEL SENIOR | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 36; -- SENTINEL PERFORMANCE LS | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 49; -- ANDERSON BEET PULP SHREDS 25LB | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 165; -- TRIPLE CROWN BALANCER GOLD 50 LB | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 221; -- Triple Crown Grass | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 167; -- TRIPLE CROWN RICE BRAN | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 164; -- TRIPLE CROWN SENIOR GOLD | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 156; -- TRIPLE CROWN STRESSFREE FORAGE 40LB | was 'other' -> 'horse'
UPDATE products SET category = 'horse' WHERE id = 507; -- TRIPLE CROWN RATION BALANCER | was 'other' -> 'horse'
UPDATE products SET category = 'fly_spray' WHERE id = 210; -- EX ULTRASHIELD ABSORBINE GAL | was 'horse' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 268; -- EX ULTRASHIELD ABSORBINE 32OZ | was 'supplement' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 365; -- ULTRASHIELD SPORT QTS | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 366; -- ULTRASHIELD RED QTS | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 122; -- MOSQUITO HALT 32OZ FARNAM | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 304; -- MOSQUITO HALT GAL FARNAM | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 264; -- ENDURE EZ POUR SWEAT RESIST GAL | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 265; -- ENDURE SWEAT RESIST FLY SPRAY 32OZ | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 169; -- TRI-TEC 14 FLY REPELLANT GAL | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 350; -- TRI-TEC 14 FLY REPELLANT 32OZ | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 233; -- BRONCO EQUINE GAL | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 232; -- BRONCO EQUINE FLY SPRAY 32OZ | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 208; -- FLYSECT SUPER 7 REP SPRAY GALLON | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 281; -- FLYSECT SUPER 7 32OZ | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 361; -- WIPE II FLY SPRAY W/CITRO | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 367; -- FARNAM NATURE'S DEFENSE QTS | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 412; -- ENDURE GOLD QT SPRAY | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 413; -- ENDURE GOLD GAL | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 292; -- HORSE & PONY FLYSPRAY GAL | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 175; -- HORSE & PONY FLY SPRAY 32OZ | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 317; -- PRO-FORCE FLY SPRAY 32OZ | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 191; -- WIPE N SPRAY PYRETHRIN GAL PYRANHA | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 362; -- ZERO BITE 32OZ PYRANHA | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_spray' WHERE id = 296; -- LEGACY FLY SPRAY 32OZ PYRANHA | was 'other' -> 'fly_spray'
UPDATE products SET category = 'fly_control' WHERE id = 336; -- SIMPLIFLY FLY CONTROL 20LB | was 'other' -> 'fly_control'
UPDATE products SET category = 'fly_control' WHERE id = 211; -- SIMPLIFLY FLY CONTROL 10LB | was 'other' -> 'fly_control'
UPDATE products SET category = 'electrolyte' WHERE id = 392; -- APPLE ELITE 5LB | was 'supplement' -> 'electrolyte'
UPDATE products SET category = 'electrolyte' WHERE id = 393; -- APPLE ELITE 7.5LB | was 'supplement' -> 'electrolyte'
UPDATE products SET category = 'electrolyte' WHERE id = 225; -- APPLE ELITE ELECTROLYTE PASTE | was 'supplement' -> 'electrolyte'
UPDATE products SET category = 'electrolyte' WHERE id = 195; -- APPLE A DAY 5LB | was 'other' -> 'electrolyte'
UPDATE products SET category = 'electrolyte' WHERE id = 163; -- APPLE A DAY 15LB | was 'other' -> 'electrolyte'
UPDATE products SET category = 'electrolyte' WHERE id = 121; -- APPLE A DAY 30LB | was 'other' -> 'electrolyte'
UPDATE products SET category = 'electrolyte' WHERE id = 224; -- APPLE DEX 30 LBS | was 'supplement' -> 'electrolyte'
UPDATE products SET category = 'electrolyte' WHERE id = 344; -- STRESS-DEX ORANGE 4LB | was 'other' -> 'electrolyte'
UPDATE products SET category = 'electrolyte' WHERE id = 391; -- STRESS DEX 12LB | was 'supplement' -> 'electrolyte'
UPDATE products SET category = 'electrolyte' WHERE id = 343; -- STRESS-DEX ORANGE 20LB | was 'other' -> 'electrolyte'
UPDATE products SET category = 'gut_health' WHERE id = 150; -- NUTRI-GARD PWDR 3 KG | was 'other' -> 'gut_health'
UPDATE products SET category = 'gut_health' WHERE id = 351; -- ULCERGARD PASTE | was 'supplement' -> 'gut_health'
UPDATE products SET category = 'gut_health' WHERE id = 319; -- PROBIOS POWDER 5LB | was 'supplement' -> 'gut_health'
UPDATE products SET category = 'gut_health' WHERE id = 318; -- PROBIOS DISPERSIBLE POWDER | was 'supplement' -> 'gut_health'
UPDATE products SET category = 'gut_health' WHERE id = 320; -- PROBIOS SOFT CHEWS 600GM | was 'supplement' -> 'gut_health'
UPDATE products SET category = 'gut_health' WHERE id = 348; -- TOTAL GUT HEALTH JAR 1.12 | was 'supplement' -> 'gut_health'
UPDATE products SET category = 'gut_health' WHERE id = 386; -- TOTAL GUT HEALTH 6.75LB | was 'supplement' -> 'gut_health'
UPDATE products SET category = 'gut_health' WHERE id = 349; -- TOTAL GUT HEALTH SYRINGE | was 'supplement' -> 'gut_health'
UPDATE products SET category = 'gut_health' WHERE id = 212; -- TOTAL PRE & PROBIOTIC 5LB RAMARD | was 'other' -> 'gut_health'
UPDATE products SET category = 'gut_health' WHERE id = 387; -- TOTAL PRE+PROBIOTICS 8OZ | was 'supplement' -> 'gut_health'
UPDATE products SET category = 'psyllium' WHERE id = 331; -- SANDCLEAR 3LBS | was 'supplement' -> 'psyllium'
UPDATE products SET category = 'psyllium' WHERE id = 330; -- SANDCLEAR 10LB | was 'supplement' -> 'psyllium'
UPDATE products SET category = 'psyllium' WHERE id = 105; -- SANDCLEAR 20LB | was 'supplement' -> 'psyllium'
UPDATE products SET category = 'psyllium' WHERE id = 332; -- SANDPURGE PSYLLIUM PELLET 5LB | was 'other' -> 'psyllium'
UPDATE products SET category = 'psyllium' WHERE id = 390; -- SAND PURGE 10LB | was 'supplement' -> 'psyllium'
UPDATE products SET category = 'supplement' WHERE id = 205; -- ELEVATE MAINTENANCE POWDER VITAMIN E 2LB | was 'other' -> 'supplement'
UPDATE products SET category = 'supplement' WHERE id = 151; -- FARRIER'S FORMULA DOUBLE STRENGTH 1LB | was 'other' -> 'supplement'
UPDATE products SET category = 'oil' WHERE id = 187; -- HEALTHY COAT HORSE GAL | was 'other' -> 'oil'
UPDATE products SET category = 'oil' WHERE id = 159; -- KARRON OIL | was 'supplement' -> 'oil'
UPDATE products SET category = 'oil' WHERE id = 129; -- RICE BRAN OIL PURE GAL | was 'other' -> 'oil'
UPDATE products SET category = 'oil' WHERE id = 203; -- KER EO-3 OMEGA-3 | was 'supplement' -> 'oil'
UPDATE products SET category = 'oil' WHERE id = 160; -- COCOSOYA GAL | was 'supplement' -> 'oil'
UPDATE products SET category = 'oil' WHERE id = 128; -- HEALTHY COAT HORSE 2.5 GAL | was 'other' -> 'oil'
UPDATE products SET category = 'oil' WHERE id = 303; -- MINERAL OIL GAL | was 'other' -> 'oil'
UPDATE products SET category = 'oil' WHERE id = 360; -- WHEAT GERM OIL GAL | was 'other' -> 'oil'
UPDATE products SET category = 'oil' WHERE id = 279; -- FLAXSEED OIL GAL | was 'other' -> 'oil'
UPDATE products SET category = 'oil' WHERE id = 400; -- LINSEED OIL GAL | was 'other' -> 'oil'
UPDATE products SET category = 'grooming' WHERE id = 188; -- SHOWSHEEN HAIR POLISH GAL | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 260; -- E3 HOOF OIL WITH BRUSH 32OZ | was 'supplement' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 308; -- MTG 32OZ | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 293; -- ICETIGHT POULTICE 7.5LB | was 'supplement' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 334; -- SHOWSHEEN DETANGLER W/ SPRAYER | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 283; -- FUNGASOL SPRAY QT | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 408; -- TUNGASOL OINTMENT | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 402; -- QUIC BRAID 16OZ SPRAY | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 235; -- CANTER MANE & TAIL COND 1L | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 236; -- CANTER MANE & TAIL COND 500ML | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 406; -- CANTER DREAM COAT 1L | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 407; -- CANTER COAT SHINE 500ML | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 405; -- COWBOY MAGIC DETANGLER AND SHINE 4OZ | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 244; -- COWBOY MAGIC GREEN SPOT REMOVER 32OZ | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 401; -- SHOWSHEEN DETANGLER GEL | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 483; -- HOOFLEX NATURAL DRESSING & CONDITIONER 15OZ | was 'supplement' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 484; -- HOOFLEX THERAPEUTIC CONDITIONER 15OZ | was 'supplement' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 459; -- TIGER'S TONGUE SPONGE | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 439; -- EZ ARNICA LIQUID | was 'other' -> 'grooming'
UPDATE products SET category = 'grooming' WHERE id = 447; -- COAT DEFENSE PASTE 24OZ | was 'other' -> 'grooming'
UPDATE products SET category = 'shampoo' WHERE id = 206; -- E3 QUICK SILVER SHAMPOO - 64OZ | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 261; -- EL QUIC SILVER SHAMPOO 16OZ | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 282; -- FUNGASOL SHAMPOO 20OZ | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 256; -- E3 ANTIBACTERIAL ANTIFUNGAL GAL | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 142; -- E3 ARGAN OIL SHAMPOO GAL | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 143; -- E3 TEA TREE SHAMPOO GAL | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 302; -- MANE & TAIL SHAMPOO GAL | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 301; -- MANE & TAIL SHAMPOO 32OZ | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 249; -- COWBOY MAGIC ROSEWATER SHAMPOO 32OZ | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 248; -- COWBOY MAGIC ROSEWATER SHAMPOO 16OZ | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 247; -- COWBOY MAGIC ROSEWATER COND GAL | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 245; -- COWBOY MAGIC ROSEWATER COND 32OZ | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 246; -- COWBOY MAGIC ROSEWATER COND 16OZ | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 257; -- E3 ANTIBACTERIAL SHAMPOO 32OZ | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 258; -- E3 ARGAN OIL SHAMPOO 32OZ | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 394; -- E3 TEA TREE OIL SHAMPOO QTS | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 259; -- E3 BRIGHTENING SHAMPOO 32OZ | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 355; -- VETROLIN BATH 32OZ | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 357; -- VETROLIN WHITE N BRITE SHAMPOO | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 271; -- FC ANIMAL SHAMPOO GAL | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 272; -- FC ANTIFUNGAL SHAMPOO GAL | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 397; -- FC ANTIFUNGAL SHAMPOO QT | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 399; -- FC CITRONELLA SHAMPOO QTS | was 'other' -> 'shampoo'
UPDATE products SET category = 'shampoo' WHERE id = 414; -- LUCKY BRAID SHAMPOO QT | was 'other' -> 'shampoo'
UPDATE products SET category = 'liniment' WHERE id = 383; -- ABSORBINE VETERINARY LINIMENT GEL 12OZ | was 'supplement' -> 'liniment'
UPDATE products SET category = 'liniment' WHERE id = 298; -- LINIMENT GALLON VETROLIN | was 'other' -> 'liniment'
UPDATE products SET category = 'liniment' WHERE id = 297; -- LINIMENT 32OZ VETROLIN | was 'other' -> 'liniment'
UPDATE products SET category = 'liniment' WHERE id = 415; -- FINISH LINE ORIGINAL PREMIUM POULTICE 5LB | was 'supplement' -> 'liniment'
UPDATE products SET category = 'clippers' WHERE id = 231; -- BLADE ULTRA EDGE T-10 | was 'other' -> 'clippers'
UPDATE products SET category = 'clippers' WHERE id = 352; -- ULTRA EDGE T-84 BLADE | was 'other' -> 'clippers'
UPDATE products SET category = 'clippers' WHERE id = 409; -- ANDIS AGC2 CLIPPER | was 'other' -> 'clippers'
UPDATE products SET category = 'clippers' WHERE id = 238; -- COOL CARE PLUS SPRAY ANDIS | was 'other' -> 'clippers'
UPDATE products SET category = 'clippers' WHERE id = 410; -- ANDIS CLIPPER BLADE CARE SPRAY | was 'other' -> 'clippers'
UPDATE products SET category = 'clippers' WHERE id = 411; -- ANDIS CLIPPER BLADE CARE DIP | was 'other' -> 'clippers'
UPDATE products SET category = 'leather' WHERE id = 370; -- BELVOIR TACK CLEANER | was 'other' -> 'leather'
UPDATE products SET category = 'leather' WHERE id = 371; -- BELVOIR TACK CONDITIONER | was 'other' -> 'leather'
UPDATE products SET category = 'leather' WHERE id = 228; -- BELVOIR TACK COND BAR SOAP | was 'other' -> 'leather'
UPDATE products SET category = 'leather' WHERE id = 373; -- BELVOIR TACK WIPES | was 'other' -> 'leather'
UPDATE products SET category = 'leather' WHERE id = 378; -- HONEYCOMB TACK SPONGE | was 'other' -> 'leather'
UPDATE products SET category = 'leather' WHERE id = 377; -- TACK SPONGE 12 PACK | was 'other' -> 'leather'
UPDATE products SET category = 'leather' WHERE id = 374; -- EQUI-CARE SADDLE SOAP 127OZ | was 'other' -> 'leather'
UPDATE products SET category = 'leather' WHERE id = 376; -- EQUI-CARE SADDLE OINTMENT 32OZ | was 'other' -> 'leather'
UPDATE products SET category = 'leather' WHERE id = 372; -- FARNHAM LEATHER NEW SPRAY GLYCERINE QTS | was 'other' -> 'leather'
UPDATE products SET category = 'leather' WHERE id = 299; -- LIQUID GLYCERIN SADDLE SOAP FIEBINGS | was 'other' -> 'leather'
UPDATE products SET category = 'leather' WHERE id = 368; -- FIEBINGS MINK OIL LIQUID 8OZ | was 'other' -> 'leather'
UPDATE products SET category = 'barn' WHERE id = 117; -- DURA FORK | was 'other' -> 'barn'
UPDATE products SET category = 'barn' WHERE id = 234; -- BROOM BLACK | was 'other' -> 'barn'
UPDATE products SET category = 'barn' WHERE id = 310; -- MUCK TUB BLACK 70QT | was 'other' -> 'barn'
UPDATE products SET category = 'barn' WHERE id = 309; -- MUCK TUB BLACK 40QT | was 'other' -> 'barn'
UPDATE products SET category = 'barn' WHERE id = 337; -- SMALL BUCKET 8QT BLACK ROUND | was 'other' -> 'barn'
UPDATE products SET category = 'barn' WHERE id = 276; -- FLAT BACK BUCKET 20QT BLACK | was 'other' -> 'barn'
UPDATE products SET category = 'barn' WHERE id = 273; -- FEED PAN 3GAL | was 'other' -> 'barn'
UPDATE products SET category = 'barn' WHERE id = 274; -- FEED PAN 4 QUART | was 'other' -> 'barn'
UPDATE products SET category = 'barn' WHERE id = 275; -- FEED PAN 8QT | was 'other' -> 'barn'
UPDATE products SET category = 'treats' WHERE id = 305; -- MRS PASTURES COOKIES 15LB BOX | was 'other' -> 'treats'
