INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('2025 2ND CUT 3 STRING', 'other', 'bale', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('3M TAPE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ALL IN ONE SHAMPOO LEAVE-IN BRAIDS 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('APPLE ELITE 20LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('AQUA-AIDE', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ASSURE GUARD', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BRONCHIX LIQUID 1LT FORAN', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CF CRIMPED OATS', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CROSS TIE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ELECTROLYTE BALL 8LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ELEVATE SE 2LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FANCY WILD BIRD 40LB', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FAST TRACK BLUE FINE SHAVINGS', 'other', 'shavings', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FLEX WRAP 12 BOXES', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FLEX WRAP BLACK', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('GUTBIOME FORAN', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('HAVENS SALT', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('HOOFLEX NATURAL DRESSING & CONDITIONER 15OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('HOOFLEX THERAPEUTIC CONDITIONER 15OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ICETIGHT 4LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('IVERMECTIN PASTE APPLE FLAVOR 1.87%', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('LIXOTONIC FORAN', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MRS PASTURES REFILL 35LB', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('NUTRICALM 2LTS FORAN', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PE CALM 3LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PE ELEMENTS 4LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PLAIN SALT BRICK', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PUSH BROOM', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PYRANHA 1-10 HP', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PYRANHA ODAWAY GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PYRANHA STOCK GUARD 64OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('QUIC SILVER WHITENING SHAMPOO GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('REPEL X QUART', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SOOTHING PINK', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('STALL MAT', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('STANDLEE ALFALFA TIMOTHY PELLETS', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('STANDLEE SMART BEET SHREDS', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('STANDLEE TIMOTHY CHOPPED', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('STANDLEE TIMOTHY GRASS PELLETS', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TC BALANCER GOLD', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TC GROWTH', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TRIPLE CROWN RATION BALANCER', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ULTIMATE RECOVERY 25 BUCKEYE', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('VITA FLEX PRO 4LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('VITAMINO BALANCER 20KG CAVALOR', 'other', 'bag', 0, 1);
