INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('2025 Timothy', 'other', 'bale', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('Proforce Fuel XF', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SafeChoice All Life Stages', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PDZ Powder', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('Endurance 14 Muesli Havens', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('Power Plus Mix 44lb Havens', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('Triple Crown Grass', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('Ultimate Finish 25 Buckeye', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ALU-MEND SPRAY BANDAGE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('APPLE DEX 30 LBS', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('APPLE ELITE ELECTROLYTE PASTE', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('B COMPLETE 1 LT FORAN', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('B COMPLETE 2.5LTS FORAN', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BELVOIR TACK COND BAR SOAP', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BETADINE SOLUTION 16OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BETADINE SOLUTION GAL', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BLADE ULTRA EDGE T-10', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BRONCO EQUINE FLY SPRAY 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BRONCO EQUINE GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BROOM BLACK', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CANTER MANE & TAIL COND 1L', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CANTER MANE & TAIL COND 500ML', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CLIPPER AGC2 SUPER EQ 2 SPEED', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COOL CARE PLUS SPRAY ANDIS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COPPER SULFATE GEL 28OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COPPERVIT 1LT FORAN', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COPPERVIT 2.5 LT FORAN', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CORNUCRESCINE HOOF OINT 2', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CORNUCRESCINE MOISTURISER', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COWBOY MAGIC GREEN SPOT REMOVER 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COWBOY MAGIC ROSEWATER COND 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COWBOY MAGIC ROSEWATER COND 16OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COWBOY MAGIC ROSEWATER COND GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COWBOY MAGIC ROSEWATER SHAMPOO 16OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COWBOY MAGIC ROSEWATER SHAMPOO 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CRUNCHIES CAVALOR', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('DECKER LARGE BODY SPONGE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('DOUBLE END BRASS SNAPS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('DURA FORK HEAD PINK', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('DURA FORK LIME GREEN', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('DURAMASK W/EARS HORSE PONY', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('E3 ANTIBACTERIAL ANTIFUNGAL GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('E3 ANTIBACTERIAL SHAMPOO 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('E3 ARGAN OIL SHAMPOO 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('E3 BRIGHTENING SHAMPOO 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('E3 HOOF OIL WITH BRUSH 32OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EL QUIC SILVER SHAMPOO 16OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EL QUICK SILVER BRAID 16OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ELEVATE MAINTENANCE POWDER 10LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ENDURE EZ POUR SWEAT RESIST GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ENDURE SWEAT RESIST FLY SPRAY 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EPSOM SALT POULTICE 10LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EQUI SOFT 127OZ EQUI CARE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EX ULTRASHIELD ABSORBINE 32OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FANCY WILD BIRD SEED', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FARRIER''S FORMULA ORIGINAL BAG', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FC ANIMAL SHAMPOO GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FC ANTIFUNGAL SHAMPOO GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FEED PAN 3GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FEED PAN 4 QUART', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FEED PAN 8QT', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FLAT BACK BUCKET 20QT BLACK', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FLAT BACK BUCKET 20QT BLUE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FLAT BACK BUCKET 20QT GREEN', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FLAXSEED OIL GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FLEX WRAP 4 INCH SINGLE ASST', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FLYSECT SUPER 7 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FUNGASOL SHAMPOO 20OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FUNGASOL SPRAY QT', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('G-CHILL 30 SERVINGS', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('GASTROADE GAL', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('GAUZE SPONGE 4X4X12 PLY', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('GERMAN HORSE MUFFINS 6LBS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('GERMAN MINTY MUFFINS 6LBS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('GIANT FLY RELIEF DISPOSABLE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('HIMALAYAN SALT - LARGE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('HIMALAYAN SALT - SMALL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('HORSE & PONY FLYSPRAY GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ICETIGHT POULTICE 7.5LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('KAUFFMANS ELECTROLYTE APPLE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('KELCIE''S SPICE 5 LB', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('LEGACY FLY SPRAY 32OZ PYRANHA', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('LINIMENT 32OZ VETROLIN', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('LINIMENT GALLON VETROLIN', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('LIQUID GLYCERIN SADDLE SOAP FIEBINGS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MANE & TAIL CONDITIONER 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MANE & TAIL SHAMPOO 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MANE & TAIL SHAMPOO GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MINERAL OIL GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MOSQUITO HALT GAL FARNAM', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MRS PASTURES COOKIES 15LB BOX', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MRS PASTURES COOKIES 15LB BUCKET', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MRS PASTURES COOKIES 2LBS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MTG 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MUCK TUB BLACK 40QT', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MUCK TUB BLACK 70QT', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MUCK TUB BLUE 70QT', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('OINTMENT 10.6OZ EQUI CARE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ONE AC 200GM', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PANACUR DEWORMER EQUINE POWER PAC', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('POVIDONE IODINE 10% 32OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PRE-FUEL LIQ 2.5 LT FORAN', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PRO-FORCE FLY SPRAY 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PROBIOS DISPERSIBLE POWDER', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PROBIOS POWDER 5LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PROBIOS SOFT CHEWS 600GM', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('QUEST GEL', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('QUEST GEL PLUS', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('RED CELL EQUINE 32OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('REDMOND DAILY GOLD STRESS', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('REDMOND ROCK CRUSHED 5LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('REDMOND ROCK ON A ROPE 3LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('REFUEL LIQ 1LT FORAN', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('REPEL XPE EMULSIFIABLE SPRAY 16OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('RESIST + VITA C 5KG CAVALOR', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SANDCLEAR 10LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SANDCLEAR 3LBS', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SANDPURGE PSYLLIUM PELLET 5LB', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SANTA FE COAT CONDITIONER ABSORBINE', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SHOWSHEEN DETANGLER W/ SPRAYER', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SHUR HOOF DRESSING 32OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SIMPLIFLY FLY CONTROL 20LB', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SMALL BUCKET 8QT BLACK ROUND', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SMALL BUCKET 8QT GREEN ROUND', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SMALL BUCKET 8QT NAVY ROUND', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SOLITUDE IGR 20LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('STAIN MASTER SPR 500ML', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('STOCK GUARD CONCENTRATE', 'other', 'bag', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('STRESS-DEX ORANGE 20LB', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('STRESS-DEX ORANGE 4LB', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('STRONGID PASTE WORMER', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('THRUSH TREATMENT BUSTER', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TOTAL CALM & FOCUS 1.12LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TOTAL GUT HEALTH JAR 1.12', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TOTAL GUT HEALTH SYRINGE', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TRI-TEC 14 FLY REPELLANT 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ULCERGARD PASTE', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ULTRA EDGE T-84 BLADE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('V.S.L. LIQ 1LT FORAN', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('V.S.L. LIQ 2.5LTS FORAN', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('VETROLIN BATH 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('VETROLIN SHINE 360 20OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('VETROLIN WHITE N BRITE SHAMPOO', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('VITA B1 CRUMBLES 3LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('VITA E + SELENIUM CRUMBLE', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('WHEAT GERM OIL GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('WIPE II FLY SPRAY W/CITRO', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ZERO BITE 32OZ PYRANHA', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ZIMECTERIN GOLD PASTE', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ZIMECTERIN PASTE 1.87%', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ULTRASHIELD SPORT QTS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ULTRASHIELD RED QTS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FARNAM NATURE''S DEFENSE QTS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FIEBINGS MINK OIL LIQUID 8OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FIEBINGS MINK OIL PASTE 6OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BELVOIR TACK CLEANER', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BELVOIR TACK CONDITIONER', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FARNHAM LEATHER NEW SPRAY GLYCERINE QTS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BELVOIR TACK WIPES', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EQUI-CARE SADDLE SOAP 127OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EQUI-CARE SADDLE OINTMENT 10.6OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EQUI-CARE SADDLE OINTMENT 32OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TACK SPONGE 12 PACK', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('HONEYCOMB TACK SPONGE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SYNNUTRA SYNCHILL DAILY 18OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SYNNUTRA SYNCHILL PASTE', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SYNNUTRA SYNCHILL G-CHILL', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MARE MAGIC 8OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ABSORBINE VETERINARY LINIMENT GEL 12OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('KOMBAT KOO', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FINISH LINE SWEAT WELL 3.3LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TOTAL GUT HEALTH 6.75LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TOTAL PRE+PROBIOTICS 8OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('KER NANO E', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('VITA B-12 CRUMBLES 3LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SAND PURGE 10LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('STRESS DEX 12LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('APPLE ELITE 5LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('APPLE ELITE 7.5LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('E3 TEA TREE OIL SHAMPOO QTS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('E3 COOLING REJUVENATING SHAMPOO QTS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MANE N TAIL CONDITIONER GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FC ANTIFUNGAL SHAMPOO QT', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FC CITRONELLA SHAMPOO GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FC CITRONELLA SHAMPOO QTS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('LINSEED OIL GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SHOWSHEEN DETANGLER GEL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('QUIC BRAID 16OZ SPRAY', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COWBOY MAGIC DETANGLER AND SHINE QT', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COWBOY MAGIC DETANGLER AND SHINE 16OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COWBOY MAGIC DETANGLER AND SHINE 4OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CANTER DREAM COAT 1L', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CANTER COAT SHINE 500ML', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TUNGASOL OINTMENT', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ANDIS AGC2 CLIPPER', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ANDIS CLIPPER BLADE CARE SPRAY', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ANDIS CLIPPER BLADE CARE DIP', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ENDURE GOLD QT SPRAY', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ENDURE GOLD GAL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('LUCKY BRAID SHAMPOO QT', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FINISH LINE ORIGINAL PREMIUM POULTICE 5LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('DAILY GOLD POWDER 5LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('REDMOND REIN WATER 5LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('KELSIES TREATS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BEET TREATS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SWEETIES CAVALOR', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FRUITIES CAVALOR', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('HEALTHY HAIR CARE MOISTURIZER 16OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('NEATSFOOT OIL 32OZ FIEBINGS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ARMA NX MAX BELL BOOTS BLACK', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ARMA NX-AIR BRUSHING BOOTS BLACK', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COTTON LEADS BLACK', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COTTON LEADS NAVY', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EZ GROOM DANDY BRUSH #2371', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EZ GROOM BODY BRUSH #2357', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('LONG BRISTLE DANDY BRUSH #2470', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('BODY WASH BRUSH WITH SPONGE #1558', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CACTUS CLOTH', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CACTUS GLOVE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('PLASTIC SWEAT SCRAPERS #17DDS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('HIPPO TONIC BLACK CURRY COMB', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('RUBBER MASSAGE GLOVE RJ MATTHEWS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('RUBBER BRAID BANDS BAGS', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COTTON ROLL', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EZ ARNICA LIQUID', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EXCALIBUR', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('KOPERTOX', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('ELASTIKON 3 INCH BY 3M', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MEDIUM LATEX GLOVES BOX', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FARNAM PURISHIELD WOUND SKIN CARE 12OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FARNAM PURISHIELD LIQUID BANDAGE 4OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('FARNAM PURISHIELD FAST ACTING SPRAY 12OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('COAT DEFENSE PASTE 24OZ', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('3X3 GAUZE SQUARES', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EPSOM SALT PASTE 20OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EPSOM SALT PASTE 10LB', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EZI GROOM PULLING COMB W/HANDLE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('WONDER DUST', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('SCREW EYES', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('DOUBLE END SNAP ZINC', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('JARS HONEY', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EQUI-CARE HOOF GREASE 33.8OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CARR DAY MARTIN STAIN MASTER 500ML', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('EQUI-CARE HOOF GREASE 11OZ', 'supplement', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TIGER''S TONGUE SPONGE', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('GRIP FIT BRUSH BY DECKER NAVY', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('LEGENDS SOFT BRUSH #2274', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('TANGLE WRANGLER COMB BRUSH', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('HIPPO TONIC TOYS ASSORTED', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('MT SHAMPOO (MANE N TAIL)', 'other', 'each', 0, 1);
INSERT OR IGNORE INTO products (name, category, unit_type, price, active) VALUES ('CM CONDITIONER', 'other', 'each', 0, 1);